#!/usr/bin/env python

# SimpleClock by Dennis Tomas, based on:
# MiniClock v. 2.0.0
# Copyright (C) 2005  Edoardo Spadolini <pedonzolo@email.it>

import findrox; findrox.version(1, 9, 6)
import sys, os

app_dir = os.path.dirname(__file__)

sys.path.insert(0, app_dir)
sys.path.insert(0, os.path.join(app_dir, 'rox-lib', 'ROX-Lib2', 'python'))

import rox

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

from simpleclock import clock

if len(sys.argv) >= 2:
    main = clock.ClockApplet(sys.argv[1])
else:
    main = clock.ClockWindow()

main.mainloop()
